// agent/core/agent-loop.js

const { execSync } = require('child_process');
const path = require('path');
const { generateResponse } = require('./llm-client');

/**
 * Executes a single cycle of the agent's operation.
 * 
 * @param {string} userInput - The text input provided by the user.
 * @returns {Promise<string>} The text response generated by the LLM for the user.
 * @throws {Error} If any step in the cycle fails.
 */
async function runAgentCycle(userInput) {
  // Basic validation for user input.
  if (!userInput || typeof userInput.trim() !== 'string' || userInput.trim() === '') {
    throw new Error("Invalid user input provided for agent cycle. Input cannot be empty.");
  }

  try {
    // 1. Retrieve context from ChromaDB via Python script
    const pythonScriptPath = path.join(__dirname, '../../backend/retrieval/dpr_pipeline.py');
    
    let context = "No specific tennis data found for this query.";
    try {
        console.log(`RAG: Searching vector database for: "${userInput}"...`);
        
        // Execute the python script and capture JSON output
        const cmd = `python3 "${pythonScriptPath}" "${userInput.replace(/"/g, '\\"')}" --json`;
        const output = execSync(cmd, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'] });
        
        const results = JSON.parse(output);
        if (Array.isArray(results) && results.length > 0) {
            const sources = [...new Set(results.map(r => r.metadata.title))].join(', ');
            console.log(`RAG: Found ${results.length} relevant chunks across: ${sources}`);
            
            context = results.map((res, i) => 
                `[Source ${i+1}: ${res.metadata.title} (${res.metadata.source_url})]\n${res.content}`
            ).join('\n\n');
        } else {
            console.log(`RAG: No specific tennis context found. Falling back to general knowledge.`);
        }
    } catch (e) {
        console.error(`RAG Error: Retrieval failed: ${e.message}`);
    }

    // 2. Build the RAG Prompt
    const ragPrompt = `
You are Federer AI, a specialized assistant focused on tennis knowledge. 
Your goal is to answer questions using the provided context as your primary source of truth.

--- RETRIEVED TENNIS CONTEXT ---
${context}
--- END OF CONTEXT ---

USER QUESTION: ${userInput}

INSTRUCTIONS:
- Use the context to provide accurate, citation-backed answers.
- If the context doesn't contain the answer, use your internal knowledge but clearly state that you are doing so.
- Be concise, professional, and maintain a "tennis expert" tone.
- When referencing the context, use citations like [Source 1].
`.trim();

    // 3. Generate the response from Gemini
    console.log(`LLM: Synthesizing answer using retrieved knowledge...`);
    const llmResponse = await generateResponse(ragPrompt);
    console.log(`LLM: Final answer generated.`);

    return llmResponse;

  } catch (error) {
    console.error(`Agent Cycle Error: ${error.message}`);
    throw error;
  }
}

// Export the updated runAgentCycle function.
module.exports = {
  runAgentCycle,
};
